create table if not exists 占いログ
(
    id      INTEGER generated by default as identity (maxvalue 9999),
    お名前   text,
    占い日 date,
    占い結果 text,
    constraint 占いログ_pk
        primary key (id)
);
